# Configuration for git-chglog
# See: https://github.com/git-chglog/git-chglog

style: github

info:
  title: "CHANGELOG"
  repository_url: "https://github.com/amaltaro/wflow_sim"

options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - docs
        - style
        - refactor
        - perf
        - test
        - chore

  commit_groups:
    title_order:
      - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - chore
    title_maps:
      feat: "Features"
      fix: "Bug Fixes"
      docs: "Documentation"
      style: "Code Style"
      refactor: "Code Refactoring"
      perf: "Performance Improvements"
      test: "Tests"
      chore: "Maintenance"
