name: Generate Release Notes

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Matches semantic versioning (e.g., 1.0.0)
      - 'v[0-9]+.[0-9]+.[0-9]+' # Matches v-prefixed semantic versioning (e.g., v1.0.0)

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to get full history for changelog
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false # Disable cache to avoid go.sum issues
      
      - name: Install git-chglog
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
      - name: Generate Changelog
        id: changelog
        run: |
          # Generate changelog with our simple, robust configuration
          git-chglog --config .chglog/config.yml --output CHANGELOG.md ${{ github.ref_name }} || {
            echo "Changelog generation failed, creating basic changelog..."
            echo "## ${{ github.ref_name }}" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "Release ${{ github.ref_name }}" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "Please ensure commits follow conventional commit format for automatic changelog generation." >> CHANGELOG.md
          }

          # Output the changelog
          CHANGELOG=$(cat CHANGELOG.md)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: false
